services:
  db:
    image: postgres:16-alpine
    container_name: blackjack-db
    environment:
      POSTGRES_DB: blackjack
      POSTGRES_USER: blackjack
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
